### ISSUE TITLE
Issue with RRLS mod

### ISSUE THREAD

**Issue by VaporeonScripts** [AzureDoom/AzureLib-Armor#13]
using azure lib armor with RRLS makes the loading bar disappear,causing infinite loading
latest rrls fabric 1.21.1 mod
latest azure-lib-armor fabric 1.21.1 mod

**Comment by AzureDoom** [comment]
No log means I can't help

**Comment by VaporeonScripts** [comment]
alright, heres the log
https://mclo.gs/K0fpKpq

**Comment by VaporeonScripts** [comment]
[22:45:02] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at it.unimi.dsi.fastutil.objects.ObjectArrayList.get(ObjectArrayList.java:382) ~[fastutil-8.5.12.jar:?]
	at mod.azure.azurelibarmor.common.internal.common.loading.object.GeometryTree.fromModel(GeometryTree.java:35) ~[azurelibarmor-fabric-1.21.1-2.3.4.jar:?]
	at mod.azure.azurelibarmor.common.internal.common.cache.AzureLibCache.lambda$loadModels$2(AzureLibCache.java:129) ~[azurelibarmor-fabric-1.21.1-2.3.4.jar:?]
	at mod.azure.azurelibarmor.common.internal.common.cache.AzureLibCache.lambda$loadResources$5(AzureLibCache.java:148) ~[azurelibarmor-fabric-1.21.1-2.3.4.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more

**Comment by AzureDoom** [comment]
Can you link the other mod in question here? Need to check something with it. and it fully goes away if you disable it?

**Comment by VaporeonScripts** [comment]
if i remove azure lib armor, it fixes it, yeah, also heres the other mod: https://modrinth.com/mod/rrls/version/5.0.7+mc1.21-fabric

**Comment by AzureDoom** [comment]
If you disable that mod exactly, does azurelib armor work then? If so, then this isn't likely something I can fix on my end.

**Comment by VaporeonScripts** [comment]
I didn't try,I can try that tomorrow

**Comment by VaporeonScripts** [comment]
tried with azure lib armor and NO rrls, the result is
![image](https://github.com/user-attachments/assets/e3aecace-a84a-45a9-8abe-c5ca668a14f1)
java.util.concurrent.CompletionException: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at it.unimi.dsi.fastutil.objects.ObjectArrayList.get(ObjectArrayList.java:382) ~[fastutil-8.5.12.jar:?]
	at mod.azure.azurelibarmor.common.internal.common.loading.object.GeometryTree.fromModel(GeometryTree.java:35) ~[azurelibarmor-fabric-1.21.1-2.3.4.jar:?]
	at mod.azure.azurelibarmor.common.internal.common.cache.AzureLibCache.lambda$loadModels$2(AzureLibCache.java:129) ~[azurelibarmor-fabric-1.21.1-2.3.4.jar:?]
	at mod.azure.azurelibarmor.common.internal.common.cache.AzureLibCache.lambda$loadResources$5(AzureLibCache.java:148) ~[azurelibarmor-fabric-1.21.1-2.3.4.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 6 more

**Comment by AzureDoom** [comment]
You will need to test in this case then, what geckolib mod you have that has broken animations. I suggest disabling them all and enabling them slowly.

**Comment by VaporeonScripts** [comment]
im using latest gecko lib version

**Comment by AzureDoom** [comment]
Please reread my previous message. I said nothing regarding version

**Comment by bonicki** [comment]
Had the same problem, enabling CreeperOverhaul causes the infinite loading
